/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export * as uniswapV2FactorySol from "./UniswapV2factory.sol";
export * as uniswapVRouter02Sol from "./UniswapV@Router02.sol";
export * as erc1155Sol from "./erc1155.sol";
export * as nftSol from "./nft.sol";
